// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, jsxs, Fragment } from 'react/jsx-runtime';
import { Link, Text, useSitecore, RichText, NextImage, Placeholder as Placeholder_8a80e63291fea86e0744df19113dc44bec187216, ServerPlaceholder, CdpHelper, withDatasourceCheck } from '@sitecore-content-sdk/nextjs';
import { Suspense, useState, useEffect } from 'react';
import React from 'react';
import Placeholder from 'components/content-sdk/Placeholder';
import { componentMap } from '.sitecore/component-map';
import client from 'src/lib/sitecore-client';
import { rsc } from 'rsc-env';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'jsxs', value: jsxs },
      { name: 'Fragment', value: Fragment },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'RichText', value: RichText },
      { name: 'NextImage', value: NextImage },
      { name: 'Placeholder', value: Placeholder_8a80e63291fea86e0744df19113dc44bec187216 },
      { name: 'ServerPlaceholder', value: ServerPlaceholder },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'Suspense', value: Suspense },
      { name: 'useState', value: useState },
      { name: 'useEffect', value: useEffect },
      { name: 'default', value: React },
    ]
  },
  {
    module: 'components/content-sdk/Placeholder',
    exports: [
      { name: 'default', value: Placeholder },
    ]
  },
  {
    module: '.sitecore/component-map',
    exports: [
      { name: 'componentMap', value: componentMap },
    ]
  },
  {
    module: 'src/lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'rsc-env',
    exports: [
      { name: 'rsc', value: rsc },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
